# Generated by Django 4.1.7 on 2023-03-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabsocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stacks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
