# Generated by Django 4.1.7 on 2023-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabsocial', '0002_post_stacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stak', models.CharField(max_length=100)),
            ],
        ),
    ]
