# Generated by Django 4.1.7 on 2023-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabsocial', '0003_stacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacks',
            name='stak',
        ),
        migrations.AddField(
            model_name='stacks',
            name='name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='post',
            name='stacks',
        ),
        migrations.AddField(
            model_name='post',
            name='stacks',
            field=models.ManyToManyField(to='collabsocial.stacks'),
        ),
    ]
