# Generated by Django 4.1.7 on 2023-03-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabsocial', '0004_remove_stacks_stak_stacks_name_remove_post_stacks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stacks',
        ),
        migrations.DeleteModel(
            name='Stacks',
        ),
    ]
