# Generated by Django 4.1.7 on 2023-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabsocial', '0005_remove_post_stacks_delete_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stacks',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
