# Generated by Django 4.1.7 on 2023-03-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_more',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
